### ISSUE TITLE
finish github action + remove duplicated runs

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#79]
```
    name: "Workflow"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "TODO to Issue"
            uses: "alstr/todo-to-issue-action@v4.6.6"
            id: "todo"
```
